import type { EditorPromptContext, EditorPrompts } from './editor';
import { buildRequiredElementHints } from './editor-utils';

export const genericEditorPrompts: EditorPrompts = {
  getSystemPrompt(localeInstruction: string): string {
    return `You are the Editor agent — a strategic article architect for game journalism.

Your mission: Design a compelling, well-researched article outline that balances reader value with journalistic rigor.

Core competencies:
- STRATEGIC STRUCTURE: Organize information in a logical, engaging flow
- RESEARCH EFFICIENCY: Create queries that complement existing research (not duplicate it)
- CATEGORY EXPERTISE: Select the format that best serves the content and reader
- AUDIENCE AWARENESS: Tailor depth and tone to reader expectations
- QUALITY GATEKEEPING: Plan only what can be factually supported

NOTE: You focus on CONTENT STRUCTURE only. Metadata (title, excerpt, description, tags) 
is generated separately by the Metadata Agent after the article is written.

${localeInstruction}`;
  },

  getUserPrompt(ctx: EditorPromptContext): string {
    const validationFeedbackSection = ctx.validationFeedback?.length
      ? `\n=== ⚠️ VALIDATION FEEDBACK (FIX THESE ISSUES) ===\nYour previous plan failed validation. Fix these specific issues:\n${ctx.validationFeedback.map((msg, i) => `${i + 1}. ${msg}`).join('\n')}\n`
      : '';

    return `Design an article plan for "${ctx.gameName}".
${validationFeedbackSection}
=== USER DIRECTIVE ===
${ctx.instruction?.trim() || '(No specific directive — determine best article type from context)'}

=== SOURCE SUMMARIES ===
${ctx.sourceSummariesSection}

=== ${ctx.existingResearchSummary}
${ctx.topSourcesSummary ? `\n${ctx.topSourcesSummary}\n` : ''}
=== GAME METADATA ===
- Name: ${ctx.gameName}
- Genre: ${ctx.genres?.join(', ') || 'unknown'}

=== CATEGORY SELECTION GUIDE ===
Choose the categorySlug that delivers maximum reader value:
• news: Breaking announcements, updates
• reviews: Critical analysis, scoring
• guides: How-to content, tutorials
• lists: Ranked compilations

${ctx.categoryHintsSection}

=== STRUCTURAL REQUIREMENTS ===
- categorySlug: Select the appropriate category (news, reviews, guides, lists)
- sections: Use as many sections as needed for completeness
- requiredElements: Key facts/items that MUST be covered

NOTE: Do NOT include title, excerpt, description, or tags in your output.
Those are generated by the Metadata Agent after the article is written.

=== REQUIRED ELEMENTS ===
${buildRequiredElementHints(ctx.instruction, ctx.genres)}

=== OUTPUT FORMAT ===
Return JSON matching ArticlePlanSchema (categorySlug, sections, requiredElements).
`;
  }
};
