import type { ArticleCategorySlug, ArticlePlan } from '../../article-plan';

/**
 * Plan with title for reviewer context.
 * The title is extracted from markdown (since it's generated by Metadata Agent after planning).
 */
export interface ArticlePlanWithTitle extends ArticlePlan {
  /** Title extracted from markdown H1 (generated by Metadata Agent) */
  readonly title: string;
}

export interface ReviewerPromptContext {
  /** Plan extended with title extracted from markdown */
  readonly plan: ArticlePlanWithTitle;
  readonly markdown: string;
  readonly researchSummary: string;
  readonly categorySlug: ArticleCategorySlug;
}

export interface ReviewerPrompts {
  getSystemPrompt(): string;
  getUserPrompt(ctx: ReviewerPromptContext): string;
}
